CONDITION = 1

ID = '40'
PARTICIPANT_NUM = '1'
ORDER = 'BF'

HRES = 1024
VRES = 768

EXPHRES = 1024
EXPVRES = 768

SCREENDISTANCE = 57
SCREENWIDTH = 30

FILEPATH = ''
PROCEDURE_PATH = 'Data/Procedures/'
FEATURE_PATH = 'Data/Images/feature_only/'
FEATURES_PLACED_PATH = 'Data/Images/Features_Placed/'
RESULTS_PATH = 'Data/Results/'
INSTRUCTIONS_PATH = 'Data/Images/Instructions/'
CONTEXTS_PATH = 'Data/Images/Context/'

SCALE = 1

INPUT_MODE = 0

OFFSET = 0
