CONDITION = 0

SUBJECT_ID = '001'

HRES = 1024
VRES = 768

EXPHRES = 1024
EXPVRES = 768

SCREENDISTANCE = 57
SCREENWIDTH = 30

FILEPATH = ''
PROCEDURE_PATH = 'Data/Procedures/'
FEATURE_PATH = 'Data/Images/Features_Placed/'
RESULTS_PATH = 'Data/Results/'
IMAGES_MAP_PATH = 'Data/imagemap.xlsx'

INPUT_MODE = 0

OFFSET = 0